cmake_minimum_required(VERSION 3.27)

message(STATUS "GEAR_CORE")

set(GEAR_CORE_SOURCE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")

add_subdirectory(Core)
add_subdirectory(Animation)
add_subdirectory(Asset)
add_subdirectory(Audio)
add_subdirectory(Graphics)
add_subdirectory(ImGui)
add_subdirectory(Input)
add_subdirectory(Objects)
add_subdirectory(Project)
add_subdirectory(Rendering)
add_subdirectory(Resources)
add_subdirectory(Scene)
add_subdirectory(Scripting)
add_subdirectory(UI)

set_target_properties(GEAR_CORE_Core PROPERTIES FOLDER "GEAR_CORE")
set_target_properties(GEAR_CORE_Animation PROPERTIES FOLDER "GEAR_CORE")
set_target_properties(GEAR_CORE_Asset PROPERTIES FOLDER "GEAR_CORE")
set_target_properties(GEAR_CORE_AssetManager PROPERTIES FOLDER "GEAR_CORE")
set_target_properties(GEAR_CORE_Audio PROPERTIES FOLDER "GEAR_CORE")
set_target_properties(GEAR_CORE_Graphics PROPERTIES FOLDER "GEAR_CORE")
set_target_properties(GEAR_CORE_ImGui PROPERTIES FOLDER "GEAR_CORE")
set_target_properties(GEAR_CORE_Input PROPERTIES FOLDER "GEAR_CORE")
set_target_properties(GEAR_CORE_Objects PROPERTIES FOLDER "GEAR_CORE")
set_target_properties(GEAR_CORE_Project PROPERTIES FOLDER "GEAR_CORE")
set_target_properties(GEAR_CORE_Rendering PROPERTIES FOLDER "GEAR_CORE")
set_target_properties(GEAR_CORE_Resources PROPERTIES FOLDER "GEAR_CORE")
set_target_properties(GEAR_CORE_Scene PROPERTIES FOLDER "GEAR_CORE")
set_target_properties(GEAR_CORE_Scripting PROPERTIES FOLDER "GEAR_CORE")
set_target_properties(GEAR_CORE_UI PROPERTIES FOLDER "GEAR_CORE")