#pragma once
#include "ContentBrowserPanel.h"
#include "ContentEditorPanel.h"
#include "MaterialPanel.h"
#include "ProjectPanel.h"
#include "PropertiesPanel.h"
#include "RendererPropertiesPanel.h"
#include "SceneHierarchyPanel.h"
#include "ViewportPanel.h"