cmake_minimum_required(VERSION 3.27)

#GEAR_NATIVE_SCRIPT
set(TARGET_NAME GEAR_NATIVE_SCRIPT)
message(STATUS "${TARGET_NAME}")

add_library(${TARGET_NAME} SHARED)

#SRC
set(SRC_HEADERS
)
set(SRC_CPP_FILES
	"DllMain.cpp"
)
target_sources(${TARGET_NAME} PRIVATE ${SRC_CPP_FILES} ${SRC_HEADERS})
source_group("src" FILES ${SRC_CPP_FILES} ${SRC_HEADERS})

#APPLICATION_NATIVE_SCRIPTS_DIR
file(GLOB APPLICATION_NATIVE_SCRIPTS_CPP_FILES 
	${APPLICATION_NATIVE_SCRIPTS_DIR}/*.cpp
)
file(GLOB APPLICATION_NATIVE_SCRIPTS_HEADERS 
	${APPLICATION_NATIVE_SCRIPTS_DIR}/*.h
)
target_sources(${TARGET_NAME} PRIVATE ${APPLICATION_NATIVE_SCRIPTS_CPP_FILES} ${APPLICATION_NATIVE_SCRIPTS_HEADERS})
source_group("ApplicationNativeScripts" FILES ${APPLICATION_NATIVE_SCRIPTS_CPP_FILES} ${APPLICATION_NATIVE_SCRIPTS_HEADERS})

target_link_libraries(${TARGET_NAME} PRIVATE
	GEAR_CORE_UI
	GEAR_CORE_Project
	GEAR_CORE_Scripting
	GEAR_CORE_Scene
	GEAR_CORE_AssetManager
	GEAR_CORE_Rendering
	GEAR_CORE_Objects
	GEAR_CORE_Graphics
	GEAR_CORE_Asset
	GEAR_CORE_Core
	MIRU_CORE
	ARC
)

target_include_directories(${TARGET_NAME} PRIVATE 
	"${GEAR_SOURCE_DIR}/GEAR_CORE"
	"${GEAR_SOURCE_DIR}/External"
	"${GEAR_SOURCE_DIR}/External/MIRU/External"
)